neyralab/gd-bot

src/components/upgradeStorage/BillingModal/styles.module.css

https://ghostdrive.atlassian.net/browse/TBOT-15

Add scroll to the payment modal

---

.gitignore
src/components/upgradeStorage/index.jsx

https://ghostdrive.atlassian.net/browse/TBOT-17

Fix upgrade storage

---

package-lock.json
package.json
src/effects/filesEffects.js
src/effects/uploadFileEffect.js

https://ghostdrive.atlassian.net/browse/TBOT-20

-fix upload via gdgateway-client

---

src/components/filesPage/index.jsx
src/effects/filesEffects.js

https://ghostdrive.atlassian.net/browse/TBOT-21

fix(TBOT-21): Fix file sorting

---

src/components/filesPage/index.jsx

https://ghostdrive.atlassian.net/browse/TBOT-21

fix(TBOT-21): Update sorting direction

---

src/App.js
src/components/filesSystemPage/style.module.css
src/effects/filesEffects.js

https://ghostdrive.atlassian.net/browse/TBOT-22

fix(TBOT-22): Fix app crashing when file preview is unavailable. Fix scroll

---

src/components/upgradeStorage/index.jsx

https://ghostdrive.atlassian.net/browse/TBOT-24

Update storage type

---

src/components/filesPage/fileItem.jsx
src/components/filesSystemPage/fileItem.jsx

https://ghostdrive.atlassian.net/browse/TBOT-10

Update share link

---

.prettierrc
src/App.js
src/components/infiniteScrollComponent/index.jsx
src/components/infiniteScrollComponent/style.module.css
src/effects/authorizeUser.js
src/effects/axiosInstance.js
src/effects/filesEffects.js
src/effects/set-token.js
src/effects/storageEffects.js
src/effects/userEffects.js
src/effects/workspaceEffects.js
src/pages/filesPage/index.jsx
src/pages/filesSystemPage/index.jsx
src/pages/filesSystemPage/style.module.css
src/pages/startPage/index.jsx
src/store/reducers/filesSlice.js
src/store/reducers/workspaceSlice.js
src/utils/api-urls.js

Add referral code applying logic.  Prevent crashes, fix small bugs with ui, update requests logic, improve logging

Add referral code applying logic + bor improvement 

---

backend/app.js
backend/commands/terms/fetchPointsData.js
backend/commands/terms/index.js
backend/commands/terms/termsMessage.js
backend/handlers/photoHandler.js
backend/handlers/textHandler.js

Reorganize and refactor command handlers on backend

Implement picture analyzer in bot

---

src/pages/game/index.jsx

get right purchase id using setinterval

---

src/pages/startPage/WalletConnect/index.jsx

Prod update

---

src/components/fileFilterPanel/index.jsx
src/pages/balance/index.jsx
src/pages/balance/styles.module.css
src/pages/boost/index.jsx
src/pages/boost/styles.module.css
src/pages/startPage/Navigator/NavigatItem.jsx
src/pages/startPage/Navigator/Navigator.jsx
src/pages/startPage/Navigator/Navigator.module.scss
src/pages/startPage/Nodes/index.jsx
src/pages/startPage/PointCounter/PointCounter.jsx
src/pages/startPage/PointCounter/PointCounter.module.css
src/pages/startPage/index.jsx
src/pages/startPage/style.module.css

TBOT-423: Add "Upgrade Storage" page appear animation ++++++ TBOT-424: Update face screen animation

---

src/pages/game/AdvertisementPlayModal/AdvertisementPlayModal.jsx
src/pages/game/AdvertisementPlayModal/AdvertisementPlayModal.module.scss
src/pages/game/index.jsx
src/store/reducers/gameSlice.js

https://ghostdrive.atlassian.net/browse/TBOT-377

TBOT-377: [FE] Implement Post-Game Video Ad Screen and Integration

---

src/pages/game/AdvertisementPlayModal/AdvertisementPlayModal.jsx
src/pages/game/AdvertisementPlayModal/AdvertisementPlayModal.module.scss

https://ghostdrive.atlassian.net/browse/TBOT-447

TBOT-447: An advertisement video does not play properly on different devices

---

src/pages/game/AdvertisementPlayModal/AdvertisementPlayModal.jsx
src/pages/game/AdvertisementPlayModal/AdvertisementPlayModal.module.scss

https://ghostdrive.atlassian.net/browse/TBOT-447

TBOT-447: An advertisement video does not play properly on different devicesAdded play button

---

src/components/ppvModal/PPVModal.jsx
src/components/ppvModal/PPVModal.module.scss
src/components/ppvModal/animations.js
src/components/ppvModal/components/CountSelector/index.jsx
src/components/ppvModal/components/CountSelector/styles.module.css
src/components/ppvModal/form.jsx
src/components/ppvModal/preloader.jsx

https://ghostdrive.atlassian.net/browse/TBOT-449

TBOT-449: Pay Per View animation (form + loader)

---

src/pages/games/GameItem/index.jsx
src/pages/games/SearchInput/index.jsx
src/pages/games/animations.js
src/pages/games/index.jsx

https://ghostdrive.atlassian.net/browse/TBOT-464

TBOT-464: Games page animation

---

src/pages/drive/components/FilesList/FilesList.module.scss
src/pages/game/AdvertisementOfferModal/AdvertisementOfferModal.jsx
src/pages/game/MainButton/MainButton.jsx
src/pages/game/index.jsx

https://ghostdrive.atlassian.net/browse/TBOT-478

TBOT-478: [FE] The advertising banner disappears after the end of the free game

---

src/pages/game/index.jsx
src/store/reducers/gameSlice.js

Remove advertisement

---

src/components/Menu/Menu.jsx

https://ghostdrive.atlassian.net/browse/TBOT-479

[TBOT-479]: Fix menu svg error

---

src/effects/introEffect.ts
src/pages/intro/index.jsx

https://ghostdrive.atlassian.net/browse/TBOT-448

[TBOT-488]: Remove wave loader at the beginning if user is not the first time visiting it

---

src/pages/language/animations.js
src/pages/language/index.jsx
src/utils/debounce.js

https://ghostdrive.atlassian.net/browse/TBOT-477

[TBOT-477]: Fix language page search animation

---

src/pages/game/index.jsx
src/store/reducers/gameSlice.js

https://ghostdrive.atlassian.net/browse/TBOT-529

[TBOT-529]: Unblock advertismenent after game is played

---

src/components/file-previews/components/VideoPlayer/VideoPlayer.jsx
src/components/file-previews/components/VideoPlayer/VideoPlayer.module.scss

https://ghostdrive.atlassian.net/browse/TBOT-531

[TBOT-531]: IPhone slider swipe is not working correctly with video

---

src/components/file-previews/PreviewSwitcher/PreviewSwitcher.jsx

https://ghostdrive.atlassian.net/browse/TBOT-532

[TBOT-532]: File menu cannot be opened when file is loading

---

src/pages/drive/components/MediaSlider/FilePreviewController/FilePreviewController.jsx

https://ghostdrive.atlassian.net/browse/TBOT-522

[TBOT-522]: The default preview is seen for a moment after loading the file content

---

src/components/file-previews/components/AudioPlayer/AudioPlayer.jsx
src/components/file-previews/components/VideoPlayer/VideoPlayer.jsx
src/pages/drive/components/MediaSlider/FilePreviewController/FilePreviewController.jsx

https://ghostdrive.atlassian.net/browse/TBOT-523

[TBOT-523]: Play video and audio issue

---

src/pages/game/AdvertisementPlayModal/AdvertisementPlayModal.jsx
src/store/reducers/gameSlice.js

https://ghostdrive.atlassian.net/browse/TBOT-538

[TBOT-538]: Integrate YouTube Ads Playback for Rewards

---

src/pages/game/Models/AmbientLight.jsx
src/pages/game/Models/BackgoundModel.jsx
src/pages/game/Models/DirectionalLight.jsx
src/pages/game/Models/FogModel.jsx
src/pages/game/Models/ShipModel.jsx
src/pages/game/Models/ShipTrailModel.jsx
src/pages/game/Models/ShipWaveModel.jsx

https://ghostdrive.atlassian.net/browse/TBOT-541

[TBOT-541]: Use only what we need from Three.js [Optimization]

---

frontend/src/store/reducers/gameSlice.js

https://ghostdrive.atlassian.net/browse/TBOT-538

TBOT-538: Integrate YouTube Ads Playback for Rewards (fix timeout syntax)

---

frontend/src/effects/advertisementEffect.ts
frontend/src/pages/game/AdvertisementOfferModal/AdvertisementOfferModal.jsx
frontend/src/pages/game/AdvertisementPlayModal/AdvertisementPlayModal.jsx
frontend/src/store/reducers/gameSlice.js

https://ghostdrive.atlassian.net/browse/TBOT-558

[TBOT-558]: Get advertisement points from backend

---

frontend/src/components/file-previews/components/PdfSliderReader/PdfSliderReader.module.scss

https://ghostdrive.atlassian.net/browse/TBOT-530

[TBOT-530]: Make PDF swipe animation (Error message fix)

---

frontend/src/effects/uploadFileEffect_v2.js
frontend/src/store/reducers/driveSlice.js

https://ghostdrive.atlassian.net/browse/TBOT-574

[TBOT-574]: When uploaded with error, unblock the uploading

---

frontend/src/components/file-previews/DefaultPreview/DefaultPreview.module.scss
frontend/src/components/file-previews/components/DefaultLoader/DefaultLoader.module.scss
frontend/src/components/file-previews/components/ImageReader/ImageReader.module.scss

https://ghostdrive.atlassian.net/browse/TBOT-582

[TBOT-582]: Image should not be dragged in file previw

---

frontend/src/pages/drive/components/MediaSlider/MediaSliderCache.jsx

https://ghostdrive.atlassian.net/browse/TBOT-584

[TBOT-584]: Limit cache items to 7

---

frontend/src/components/file-previews/AudioPreview/AudioPreview.jsx
frontend/src/components/file-previews/PreviewSwitcher/PreviewSwitcher.jsx
frontend/src/components/file-previews/VideoPreview/VideoPreview.jsx
frontend/src/components/file-previews/components/AudioPlayer/AudioPlayer.jsx
frontend/src/components/file-previews/components/VideoPlayer/VideoPlayer.jsx
frontend/src/config/audio-file-extensions.js
frontend/src/config/video-file-extensions.js
frontend/src/utils/preview.js

https://ghostdrive.atlassian.net/browse/TBOT-549

[TBOT-549]: [FE] No message for files that do not have a preview

---

frontend/src/pages/drive/components/MediaSlider/MediaSlider.module.scss
frontend/src/pages/drive/components/MediaSlider/Slide/Slide.module.scss

https://ghostdrive.atlassian.net/browse/TBOT-578

[TBOT-578]: iPhone slider bottom gap

---

frontend/src/pages/game/index.jsx
frontend/src/store/reducers/gameSlice.js

https://ghostdrive.atlassian.net/browse/TBOT-548

[TBOT-548]: Switch page while playing issue

---

frontend/src/effects/filesEffects.js
frontend/src/pages/drive/components/MediaSlider/FilePreviewController/FilePreviewController.jsx
frontend/src/pages/paidView/index.jsx

https://ghostdrive.atlassian.net/browse/TBOT-583

[TBOT-583]: Change file preview function effect

---

frontend/src/components/AssistantDashboard/TemporaryControls/TemporaryControls.jsx
frontend/src/pages/startPage/index.jsx
frontend/src/pages/startPage/style.module.css

https://ghostdrive.atlassian.net/browse/TBOT-605

[TBOT-605]: Create background for the new design (added hidden button)

---

backend/app.js

https://ghostdrive.atlassian.net/browse/TBOT-636

Change ref link on prod [hot-fix]

---

frontend/src/components/segmented/styles.module.css
frontend/src/pages/earn/styles.module.css

https://ghostdrive.atlassian.net/browse/TBOT-663

[TBOT-663]: [FE]  Change the process of loading the “Earn more points” page

---

frontend/src/App.css
frontend/src/components/MenuControls/MenuControls.jsx
frontend/src/components/MenuControls/MenuControls.module.scss
frontend/src/pages/assistant/Assistant/Assistant.jsx
frontend/src/pages/assistant/Assistant/Equalizer/Equalizer.jsx
frontend/src/pages/assistant/AssistantAudio/AssistantAudio.jsx
frontend/src/pages/assistant/AssistantPage.module.scss
frontend/src/pages/assistant/CirclularPanel/CirclularPanel.jsx
frontend/src/pages/assistant/Navigation/Navigation.jsx
frontend/src/pages/assistant/Navigation/Navigation.module.scss

https://ghostdrive.atlassian.net/browse/TBOT-653
Combined with
https://ghostdrive.atlassian.net/browse/TBOT-665

[TBOT-653]: [FE] Voice recording does not work on the home screen

---

frontend/src/components/MenuControls/MainButton/MainButton.jsx
frontend/src/components/MenuControls/MainButton/MainButton.module.scss
frontend/src/components/MenuControls/MenuControls.jsx
frontend/src/components/MenuControls/MenuControls.module.scss
frontend/src/components/UploadAction/UploadAction.jsx
frontend/src/pages/assistant/AssistantAudio/AssistantAudio.jsx

https://ghostdrive.atlassian.net/browse/TBOT-666

[TBOT-666]: [FE] Add animation for voice button
